import { Environment } from './Environment';
import { scenes } from '../data/scenes';
import { Icon } from './Icon';
import type { StoryId } from '../types/game';
export function IntroScene({onStart,storyId='paris'}:{onStart:()=>void;storyId?:StoryId}){
 if(storyId==='club')return <main className="intro intro-club"><div className="intro-copy"><div className="eyebrow"><span className="tiny-line"/>YOUR NIGHT OUT STARTS WITH BONSOIR</div><h1>Not on<br/><em>the list.</em></h1><p className="intro-subtitle">Talk your way into a Paris night.</p><div className="intro-mission"><span className="mission-stamp"><Icon name="music" size={24}/></span><div><h2>Your friends are already inside.</h2><p>You’re outside Le Velours in your comfiest sneakers.<br/>The bouncer takes one look… and shakes his head.<br/><strong>Your only way in is your French.</strong></p></div></div><button className="primary-button start-button" onClick={onStart}>Walk up to the door<Icon name="arrow" size={21}/></button><div className="intro-meta"><span>🇫🇷 French</span><span>Beginner / A1</span><span><Icon name="mic" size={14}/> Voice-first</span></div><div className="intro-footnote">No perfect grammar required. Just a little courage.</div></div><div className="intro-visual"><Environment scene={scenes.club_refused} intro/><div className="postcard-label"><Icon name="pin" size={15}/><span>OBERKAMPF, PARIS</span><span className="postcard-coordinates">48°51′ N · 2°22′ E</span></div><div className="intro-floating-card"><span>👟</span><div><small>THE MISSION</small><strong>Get past the bouncer — and his dress code.</strong></div></div><span className="illustration-credit">A city that never quite sleeps.</span></div></main>
 const party=storyId==='first_party';
 const scene=party?scenes.party_arrival:scenes.street_recommendation;
 return <main className="intro"><div className="intro-copy"><div className="eyebrow"><span className="tiny-line"/>{party?'YOUR FIRST FRENCH PARTY STARTS WITH BONJOUR':'YOUR NEXT ADVENTURE STARTS WITH BONJOUR'}</div><h1>{party?<>Your first<br/><em>party.</em></>:<>Lost in<br/><em>Paris.</em></>}</h1><p className="intro-subtitle">{party?'Meet someone new. In French.':'Learn French by living through it.'}</p><div className="intro-mission"><span className="mission-stamp"><Icon name={party?'spark':'battery'} size={24}/></span><div><h2>{party?'You only know the host.':'Your phone just died.'}</h2><p>{party?<>The music is good, the snacks look great, and everyone is speaking French.<br/>Say bonjour, meet someone new, and find your place in the conversation.<br/><strong>Small talk is a big first step.</strong></>:<>Somewhere nearby is the best croissant in Paris.<br/>No maps. No translation app. No battery.<br/><strong>Your only tool is your French.</strong></>}</p></div></div><button className="primary-button start-button" onClick={onStart}>{party?'Meet your first guest':'Start the adventure'}<Icon name="arrow" size={21}/></button><div className="intro-meta"><span>🇫🇷 French</span><span>Beginner / A1</span><span><Icon name="mic" size={14}/> Voice-first</span></div><div className="intro-footnote">{party?'Simple phrases are enough to join in.':'No perfect grammar required. Just a little courage.'}</div></div><div className="intro-visual"><Environment scene={scene} intro/><div className="postcard-label"><Icon name="pin" size={15}/><span>{party?'LE MARAIS · CE SOIR':'LE MARAIS, PARIS'}</span>{!party&&<span className="postcard-coordinates">48°51′ N · 2°21′ E</span>}</div><div className="intro-floating-card"><span>{party?'🎉':'🥐'}</span><div><small>THE MISSION</small><strong>{party?'Make a new friend, one bonjour at a time.':'Follow the scent of a good croissant.'}</strong></div></div><span className="illustration-credit">{party?'A little courage. A whole new conversation.':'A city to discover. A language to live.'}</span></div></main>
}
